In [ ]:
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [8]:
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [9]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [11]:
X = df.drop('Outcome', axis=1)
y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")

X_train shape: (614, 8)
X_test shape: (154, 8)

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
# Define the objective function for Optuna
def objective(trial):
    # Suggest hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 1, 50)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 20)
    
    # Create the model with the suggested hyperparameters
    model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth,
                                   min_samples_split=min_samples_split, random_state=42)
    
    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy')
    return score.mean()

In [15]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())
# Optimize the objective function
study.optimize(objective, n_trials=50)

[I 2025-03-30 02:48:15,003] A new study created in memory with name: no-name-eca5a5e3-b2d5-4315-9264-c28e1d22838b
[I 2025-03-30 02:48:16,093] Trial 0 finished with value: 0.7638544582167134 and parameters: {'n_estimators': 109, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 0 with value: 0.7638544582167134.
[I 2025-03-30 02:48:17,171] Trial 1 finished with value: 0.7704118352658936 and parameters: {'n_estimators': 107, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 1 with value: 0.7704118352658936.
[I 2025-03-30 02:48:18,654] Trial 2 finished with value: 0.7720245235239238 and parameters: {'n_estimators': 142, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 2 with value: 0.7720245235239238.
[I 2025-03-30 02:48:20,611] Trial 3 finished with value: 0.7703985072637611 and parameters: {'n_estimators': 183, 'max_depth': 22, 'min_samples_split': 9}. Best is trial 2 with value: 0.7720245235239238.
[I 2025-03-30 02:48:22,525] Trial 4 finished with value: 0.7671598027455685 and parameters: {'n_estimators': 194, 'max_depth': 40, 'min_samples_split': 18}. Best is trial 2 with value: 0.7720245235239238.
[I 2025-03-30 02:48:24,268] Trial 5 finished with value: 0.767146474743436 and parameters: {'n_estimators': 196, 'max_depth': 41, 'min_samples_split': 20}. Best is trial 2 with value: 0.7720245235239238.
[I 2025-03-30 02:48:25,077] Trial 6 finished with value: 0.7752898840463814 and parameters: {'n_estimators': 91, 'max_depth': 8, 'min_samples_split': 15}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:26,435] Trial 7 finished with value: 0.7736238837798214 and parameters: {'n_estimators': 131, 'max_depth': 20, 'min_samples_split': 12}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:28,034] Trial 8 finished with value: 0.7704251632680262 and parameters: {'n_estimators': 152, 'max_depth': 22, 'min_samples_split': 5}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:29,095] Trial 9 finished with value: 0.7573237371717979 and parameters: {'n_estimators': 98, 'max_depth': 15, 'min_samples_split': 2}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:29,624] Trial 10 finished with value: 0.7622417699586832 and parameters: {'n_estimators': 59, 'max_depth': 4, 'min_samples_split': 14}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:30,214] Trial 11 finished with value: 0.7459549513527921 and parameters: {'n_estimators': 71, 'max_depth': 2, 'min_samples_split': 14}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:31,617] Trial 12 finished with value: 0.7736638677862187 and parameters: {'n_estimators': 134, 'max_depth': 30, 'min_samples_split': 14}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:32,506] Trial 13 finished with value: 0.7720378515260562 and parameters: {'n_estimators': 85, 'max_depth': 33, 'min_samples_split': 16}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:34,069] Trial 14 finished with value: 0.7703851792616286 and parameters: {'n_estimators': 154, 'max_depth': 28, 'min_samples_split': 11}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:35,277] Trial 15 finished with value: 0.7736638677862187 and parameters: {'n_estimators': 122, 'max_depth': 47, 'min_samples_split': 16}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:37,005] Trial 16 finished with value: 0.7704118352658936 and parameters: {'n_estimators': 169, 'max_depth': 16, 'min_samples_split': 13}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:37,915] Trial 17 finished with value: 0.7720511795281888 and parameters: {'n_estimators': 90, 'max_depth': 29, 'min_samples_split': 17}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:38,427] Trial 18 finished with value: 0.7606690657070506 and parameters: {'n_estimators': 50, 'max_depth': 37, 'min_samples_split': 20}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:39,735] Trial 19 finished with value: 0.7736771957883514 and parameters: {'n_estimators': 120, 'max_depth': 49, 'min_samples_split': 10}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:40,895] Trial 20 finished with value: 0.7606290817006531 and parameters: {'n_estimators': 114, 'max_depth': 48, 'min_samples_split': 7}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:42,285] Trial 21 finished with value: 0.7687591630014661 and parameters: {'n_estimators': 133, 'max_depth': 50, 'min_samples_split': 10}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:43,074] Trial 22 finished with value: 0.7736372117819539 and parameters: {'n_estimators': 78, 'max_depth': 42, 'min_samples_split': 15}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:44,135] Trial 23 finished with value: 0.7720645075303212 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 12}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:45,446] Trial 24 finished with value: 0.7655204584832733 and parameters: {'n_estimators': 123, 'max_depth': 15, 'min_samples_split': 6}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:47,012] Trial 25 finished with value: 0.7703985072637611 and parameters: {'n_estimators': 158, 'max_depth': 25, 'min_samples_split': 10}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:48,569] Trial 26 finished with value: 0.7671331467413035 and parameters: {'n_estimators': 141, 'max_depth': 36, 'min_samples_split': 18}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:49,802] Trial 27 finished with value: 0.7736638677862187 and parameters: {'n_estimators': 115, 'max_depth': 44, 'min_samples_split': 13}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:50,791] Trial 28 finished with value: 0.7703585232573638 and parameters: {'n_estimators': 94, 'max_depth': 18, 'min_samples_split': 11}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:51,866] Trial 29 finished with value: 0.7704251632680262 and parameters: {'n_estimators': 107, 'max_depth': 9, 'min_samples_split': 15}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:52,658] Trial 30 finished with value: 0.7655204584832733 and parameters: {'n_estimators': 72, 'max_depth': 37, 'min_samples_split': 9}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:53,895] Trial 31 finished with value: 0.7703851792616285 and parameters: {'n_estimators': 123, 'max_depth': 46, 'min_samples_split': 16}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:55,272] Trial 32 finished with value: 0.7655337864854058 and parameters: {'n_estimators': 138, 'max_depth': 46, 'min_samples_split': 17}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:56,452] Trial 33 finished with value: 0.7736638677862187 and parameters: {'n_estimators': 118, 'max_depth': 50, 'min_samples_split': 14}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:57,505] Trial 34 finished with value: 0.7703851792616287 and parameters: {'n_estimators': 106, 'max_depth': 11, 'min_samples_split': 18}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:48:59,305] Trial 35 finished with value: 0.7720378515260562 and parameters: {'n_estimators': 148, 'max_depth': 30, 'min_samples_split': 15}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:49:00,673] Trial 36 finished with value: 0.7687591630014661 and parameters: {'n_estimators': 170, 'max_depth': 25, 'min_samples_split': 8}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:49:01,789] Trial 37 finished with value: 0.7736638677862187 and parameters: {'n_estimators': 128, 'max_depth': 40, 'min_samples_split': 13}. Best is trial 6 with value: 0.7752898840463814.
[I 2025-03-30 02:49:03,098] Trial 38 finished with value: 0.7785285885645741 and parameters: {'n_estimators': 165, 'max_depth': 34, 'min_samples_split': 12}. Best is trial 38 with value: 0.7785285885645741.
[I 2025-03-30 02:49:04,486] Trial 39 finished with value: 0.7801679328268692 and parameters: {'n_estimators': 185, 'max_depth': 34, 'min_samples_split': 12}. Best is trial 39 with value: 0.7801679328268692.
[I 2025-03-30 02:49:05,980] Trial 40 finished with value: 0.7785419165667067 and parameters: {'n_estimators': 187, 'max_depth': 35, 'min_samples_split': 12}. Best is trial 39 with value: 0.7801679328268692.
[I 2025-03-30 02:49:07,426] Trial 41 finished with value: 0.7801679328268692 and parameters: {'n_estimators': 185, 'max_depth': 33, 'min_samples_split': 12}. Best is trial 39 with value: 0.7801679328268692.
[I 2025-03-30 02:49:08,825] Trial 42 finished with value: 0.7785419165667067 and parameters: {'n_estimators': 186, 'max_depth': 34, 'min_samples_split': 12}. Best is trial 39 with value: 0.7801679328268692.
[I 2025-03-30 02:49:10,291] Trial 43 finished with value: 0.7785419165667067 and parameters: {'n_estimators': 188, 'max_depth': 34, 'min_samples_split': 12}. Best is trial 39 with value: 0.7801679328268692.
[I 2025-03-30 02:49:11,752] Trial 44 finished with value: 0.7785419165667067 and parameters: {'n_estimators': 187, 'max_depth': 34, 'min_samples_split': 12}. Best is trial 39 with value: 0.7801679328268692.
[I 2025-03-30 02:49:13,119] Trial 45 finished with value: 0.7671331467413035 and parameters: {'n_estimators': 181, 'max_depth': 32, 'min_samples_split': 9}. Best is trial 39 with value: 0.7801679328268692.
[I 2025-03-30 02:49:14,624] Trial 46 finished with value: 0.7703985072637611 and parameters: {'n_estimators': 200, 'max_depth': 38, 'min_samples_split': 11}. Best is trial 39 with value: 0.7801679328268692.
[I 2025-03-30 02:49:16,022] Trial 47 finished with value: 0.7671598027455684 and parameters: {'n_estimators': 179, 'max_depth': 27, 'min_samples_split': 13}. Best is trial 39 with value: 0.7801679328268692.
[I 2025-03-30 02:49:17,437] Trial 48 finished with value: 0.7720245235239236 and parameters: {'n_estimators': 188, 'max_depth': 32, 'min_samples_split': 10}. Best is trial 39 with value: 0.7801679328268692.
[I 2025-03-30 02:49:18,769] Trial 49 finished with value: 0.7720378515260563 and parameters: {'n_estimators': 175, 'max_depth': 35, 'min_samples_split': 11}. Best is trial 39 with value: 0.7801679328268692.

In [16]:
print("Best hyperparameters: ", study.best_params)
print("Best accuracy: ", study.best_value)

Best hyperparameters:  {'n_estimators': 185, 'max_depth': 34, 'min_samples_split': 12}
Best accuracy:  0.7801679328268692

In [17]:
from sklearn.metrics import accuracy_score
# Train the model with the best hyperparameters
best_model = RandomForestClassifier(**study.best_params, random_state=42)
best_model.fit(X_train, y_train)
# Make predictions on the test set
y_pred = best_model.predict(X_test)
# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Test set accuracy: {accuracy:.4f}")

Test set accuracy: 0.7662

In [ ]:
# more sampler
# https://optuna.readthedocs.io/en/stable/reference/samplers.html
# https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/002_configurations.html

# study = optuna.create_study(direction="maximize", sampler=optuna.samplers.RandomSampler())
# study = optuna.create_study(direction="maximize", sampler=optuna.samplers.GridSampler())
# study = optuna.create_study(direction="maximize", sampler=optuna.samplers.CmaEsSampler())
# study = optuna.create_study(direction="maximize", sampler=optuna.samplers.NSGAIISampler())

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [19]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-03-30 03:05:29,397] A new study created in memory with name: no-name-3b4c63ed-ace3-41b2-b49b-a988f77ca882
[I 2025-03-30 03:05:29,945] Trial 0 finished with value: 0.7736091184441256 and parameters: {'n_estimators': 89, 'max_depth': 20}. Best is trial 0 with value: 0.7736091184441256.
[I 2025-03-30 03:05:30,302] Trial 1 finished with value: 0.7736091184441256 and parameters: {'n_estimators': 71, 'max_depth': 6}. Best is trial 0 with value: 0.7736091184441256.
[I 2025-03-30 03:05:30,805] Trial 2 finished with value: 0.7556910569105691 and parameters: {'n_estimators': 117, 'max_depth': 4}. Best is trial 0 with value: 0.7736091184441256.
[I 2025-03-30 03:05:31,355] Trial 3 finished with value: 0.7768770923003347 and parameters: {'n_estimators': 110, 'max_depth': 18}. Best is trial 3 with value: 0.7768770923003347.
[I 2025-03-30 03:05:31,927] Trial 4 finished with value: 0.7768850629682768 and parameters: {'n_estimators': 112, 'max_depth': 17}. Best is trial 4 with value: 0.7768850629682768.
[I 2025-03-30 03:05:32,338] Trial 5 finished with value: 0.763845050215208 and parameters: {'n_estimators': 86, 'max_depth': 7}. Best is trial 4 with value: 0.7768850629682768.
[I 2025-03-30 03:05:32,641] Trial 6 finished with value: 0.7801450661565439 and parameters: {'n_estimators': 64, 'max_depth': 12}. Best is trial 6 with value: 0.7801450661565439.
[I 2025-03-30 03:05:33,082] Trial 7 finished with value: 0.7703650565917424 and parameters: {'n_estimators': 98, 'max_depth': 6}. Best is trial 6 with value: 0.7801450661565439.
[I 2025-03-30 03:05:33,523] Trial 8 finished with value: 0.7703491152558585 and parameters: {'n_estimators': 94, 'max_depth': 14}. Best is trial 6 with value: 0.7801450661565439.
[I 2025-03-30 03:05:34,377] Trial 9 finished with value: 0.7784871672246134 and parameters: {'n_estimators': 134, 'max_depth': 20}. Best is trial 6 with value: 0.7801450661565439.
[I 2025-03-30 03:05:35,283] Trial 10 finished with value: 0.7768691216323927 and parameters: {'n_estimators': 119, 'max_depth': 15}. Best is trial 6 with value: 0.7801450661565439.
[I 2025-03-30 03:05:35,691] Trial 11 finished with value: 0.7785110792284393 and parameters: {'n_estimators': 65, 'max_depth': 13}. Best is trial 6 with value: 0.7801450661565439.
[I 2025-03-30 03:05:36,355] Trial 12 finished with value: 0.7686991869918699 and parameters: {'n_estimators': 131, 'max_depth': 5}. Best is trial 6 with value: 0.7801450661565439.
[I 2025-03-30 03:05:36,885] Trial 13 finished with value: 0.7752351347042882 and parameters: {'n_estimators': 96, 'max_depth': 16}. Best is trial 6 with value: 0.7801450661565439.
[I 2025-03-30 03:05:37,591] Trial 14 finished with value: 0.7850231149370317 and parameters: {'n_estimators': 116, 'max_depth': 14}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:38,367] Trial 15 finished with value: 0.7752112227004623 and parameters: {'n_estimators': 163, 'max_depth': 6}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:39,075] Trial 16 finished with value: 0.7589510600988363 and parameters: {'n_estimators': 184, 'max_depth': 4}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:39,557] Trial 17 finished with value: 0.7638370795472661 and parameters: {'n_estimators': 113, 'max_depth': 7}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:40,107] Trial 18 finished with value: 0.7703650565917424 and parameters: {'n_estimators': 74, 'max_depth': 11}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:41,166] Trial 19 finished with value: 0.7752112227004623 and parameters: {'n_estimators': 187, 'max_depth': 11}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:41,931] Trial 20 finished with value: 0.7784552845528455 and parameters: {'n_estimators': 153, 'max_depth': 10}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:42,340] Trial 21 finished with value: 0.7736091184441256 and parameters: {'n_estimators': 80, 'max_depth': 12}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:43,017] Trial 22 finished with value: 0.78012912482066 and parameters: {'n_estimators': 128, 'max_depth': 14}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:43,969] Trial 23 finished with value: 0.7687071576598119 and parameters: {'n_estimators': 190, 'max_depth': 17}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:44,532] Trial 24 finished with value: 0.7752431053722302 and parameters: {'n_estimators': 109, 'max_depth': 12}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:45,510] Trial 25 finished with value: 0.7719591901801371 and parameters: {'n_estimators': 175, 'max_depth': 15}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:45,857] Trial 26 finished with value: 0.7687230989956958 and parameters: {'n_estimators': 66, 'max_depth': 19}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:46,244] Trial 27 finished with value: 0.7670970827355332 and parameters: {'n_estimators': 71, 'max_depth': 7}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:46,577] Trial 28 finished with value: 0.7687230989956958 and parameters: {'n_estimators': 61, 'max_depth': 18}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:46,873] Trial 29 finished with value: 0.7752271640363463 and parameters: {'n_estimators': 53, 'max_depth': 18}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:48,004] Trial 30 finished with value: 0.7784712258887295 and parameters: {'n_estimators': 175, 'max_depth': 11}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:48,903] Trial 31 finished with value: 0.7507970667941973 and parameters: {'n_estimators': 196, 'max_depth': 3}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:49,566] Trial 32 finished with value: 0.7736011477761836 and parameters: {'n_estimators': 127, 'max_depth': 6}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:50,044] Trial 33 finished with value: 0.7703570859238004 and parameters: {'n_estimators': 74, 'max_depth': 6}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:50,932] Trial 34 finished with value: 0.7703331739199745 and parameters: {'n_estimators': 169, 'max_depth': 20}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:51,354] Trial 35 finished with value: 0.7670891120675912 and parameters: {'n_estimators': 93, 'max_depth': 7}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:51,896] Trial 36 finished with value: 0.7703411445879165 and parameters: {'n_estimators': 109, 'max_depth': 8}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:52,454] Trial 37 finished with value: 0.7736011477761836 and parameters: {'n_estimators': 122, 'max_depth': 18}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:53,293] Trial 38 finished with value: 0.780113183484776 and parameters: {'n_estimators': 176, 'max_depth': 13}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:53,851] Trial 39 finished with value: 0.7703491152558585 and parameters: {'n_estimators': 124, 'max_depth': 11}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:54,150] Trial 40 finished with value: 0.7670731707317073 and parameters: {'n_estimators': 59, 'max_depth': 5}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:54,641] Trial 41 finished with value: 0.7736091184441256 and parameters: {'n_estimators': 102, 'max_depth': 14}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:55,492] Trial 42 finished with value: 0.771967160848079 and parameters: {'n_estimators': 192, 'max_depth': 19}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:56,207] Trial 43 finished with value: 0.7752271640363463 and parameters: {'n_estimators': 160, 'max_depth': 15}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:56,828] Trial 44 finished with value: 0.7833731866730432 and parameters: {'n_estimators': 140, 'max_depth': 13}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:57,494] Trial 45 finished with value: 0.7768611509644509 and parameters: {'n_estimators': 137, 'max_depth': 20}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:58,325] Trial 46 finished with value: 0.7687071576598119 and parameters: {'n_estimators': 148, 'max_depth': 9}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:58,682] Trial 47 finished with value: 0.7507970667941973 and parameters: {'n_estimators': 78, 'max_depth': 3}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:59,080] Trial 48 finished with value: 0.7833891280089271 and parameters: {'n_estimators': 71, 'max_depth': 13}. Best is trial 14 with value: 0.7850231149370317.
[I 2025-03-30 03:05:59,400] Trial 49 finished with value: 0.7670891120675912 and parameters: {'n_estimators': 70, 'max_depth': 5}. Best is trial 14 with value: 0.7850231149370317.

In [20]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7850231149370317
Best hyperparameters: {'n_estimators': 116, 'max_depth': 14}

In [21]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

In [22]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [23]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2025-03-30 03:06:49,189] A new study created in memory with name: no-name-e3fbdfe4-d3d5-417b-b474-02f156408348
[I 2025-03-30 03:06:49,722] Trial 0 finished with value: 0.7654391838036028 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7654391838036028.
[I 2025-03-30 03:06:50,486] Trial 1 finished with value: 0.7735772357723577 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 1 with value: 0.7735772357723577.
[I 2025-03-30 03:06:50,798] Trial 2 finished with value: 0.7687151283277539 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 1 with value: 0.7735772357723577.
[I 2025-03-30 03:06:51,309] Trial 3 finished with value: 0.7752351347042882 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 3 with value: 0.7752351347042882.
[I 2025-03-30 03:06:51,809] Trial 4 finished with value: 0.7703491152558585 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 3 with value: 0.7752351347042882.
[I 2025-03-30 03:06:52,061] Trial 5 finished with value: 0.7817391997449387 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-03-30 03:06:52,715] Trial 6 finished with value: 0.7719591901801371 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-03-30 03:06:53,433] Trial 7 finished with value: 0.7719591901801371 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-03-30 03:06:54,124] Trial 8 finished with value: 0.7784791965566714 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-03-30 03:06:55,022] Trial 9 finished with value: 0.7784712258887295 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-03-30 03:06:55,928] Trial 10 finished with value: 0.7719591901801371 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-03-30 03:06:56,857] Trial 11 finished with value: 0.7768611509644509 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-03-30 03:06:57,770] Trial 12 finished with value: 0.7768452096285668 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-03-30 03:06:58,004] Trial 13 finished with value: 0.7703411445879165 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-03-30 03:06:58,492] Trial 14 finished with value: 0.7752351347042882 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 5 with value: 0.7817391997449387.
[I 2025-03-30 03:06:58,748] Trial 15 finished with value: 0.7752112227004623 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 5 with value: 0.7817391997449387.

In [24]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7817391997449387
Best hyperparameters: {'n_estimators': 50, 'max_depth': 10}

In [25]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

## Optuna Visualization

In [26]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [27]:
# 1. Optimization History
plot_optimization_history(study)

In [28]:
# 2. Parallel Coordinate Plot
plot_parallel_coordinate(study)

In [29]:
# 3. Slice Plot
plot_slice(study)

In [30]:
# 4. Contour Plot
plot_contour(study)

In [31]:
# 5. Parameter Importances
plot_param_importances(study)

## Optimizing ML Models

In [36]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

<frozen importlib._bootstrap>:488: RuntimeWarning:

numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 232 from PyObject

In [40]:
# Define the objective function for Optuna
def objective(trial):

    # Suggest a classifier
    classifier_name = trial.suggest_categorical('classifier', [
        'RandomForestClassifier',
        'GradientBoostingClassifier',
        'SVC',
        'LogisticRegression',
        'DecisionTreeClassifier',
        'KNeighborsClassifier',
        'XGBClassifier',
        'LGBMClassifier',
        'CatBoostClassifier'
    ])
    # Suggest hyperparameters based on the classifier

    if classifier_name == 'RandomForestClassifier':
        n_estimators = trial.suggest_int('n_estimators', 50, 200)
        max_depth = trial.suggest_int('max_depth', 1, 50)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 20)
        model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth,
                                       min_samples_split=min_samples_split, random_state=42)
    elif classifier_name == 'GradientBoostingClassifier':
        n_estimators = trial.suggest_int('n_estimators', 50, 200)
        max_depth = trial.suggest_int('max_depth', 1, 50)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
        model = GradientBoostingClassifier(n_estimators=n_estimators, max_depth=max_depth,
                                           learning_rate=learning_rate, random_state=42)
    elif classifier_name == 'SVC':
        C = trial.suggest_float('C', 1e-5, 1e5, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'poly', 'rbf', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])
        model = SVC(C=C, kernel=kernel, gamma=gamma, random_state=42)
    elif classifier_name == 'LogisticRegression':
        C = trial.suggest_float('C', 1e-5, 1e5, log=True)
        solver = trial.suggest_categorical('solver', ['liblinear', 'saga'])
        model = LogisticRegression(C=C, solver=solver, random_state=42)
    elif classifier_name == 'DecisionTreeClassifier':
        max_depth = trial.suggest_int('max_depth', 1, 50)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 20)
        model = DecisionTreeClassifier(max_depth=max_depth, min_samples_split=min_samples_split,
                                        random_state=42)
    elif classifier_name == 'KNeighborsClassifier':
        n_neighbors = trial.suggest_int('n_neighbors', 1, 50)
        weights = trial.suggest_categorical('weights', ['uniform', 'distance'])
        model = KNeighborsClassifier(n_neighbors=n_neighbors, weights=weights)
    elif classifier_name == 'XGBClassifier':
        n_estimators = trial.suggest_int('n_estimators', 50, 200)
        max_depth = trial.suggest_int('max_depth', 1, 50)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
        model = XGBClassifier(n_estimators=n_estimators, max_depth=max_depth,
                              learning_rate=learning_rate, random_state=42)
    elif classifier_name == 'LGBMClassifier':
        n_estimators = trial.suggest_int('n_estimators', 50, 200)
        max_depth = trial.suggest_int('max_depth', 1, 50)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
        model = LGBMClassifier(n_estimators=n_estimators, max_depth=max_depth,
                               learning_rate=learning_rate, random_state=42)
    elif classifier_name == 'CatBoostClassifier':
        n_estimators = trial.suggest_int('n_estimators', 50, 200)
        depth = trial.suggest_int('depth', 1, 16)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
        model = CatBoostClassifier(n_estimators=n_estimators, depth=depth,
                                   learning_rate=learning_rate, verbose=0, random_state=42)
    else:
        raise ValueError(f"Unknown classifier: {classifier_name}")

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy')
    return score.mean()

In [42]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())
# Optimize the objective function
study.optimize(objective, n_trials=5)

[I 2025-03-30 03:19:57,958] A new study created in memory with name: no-name-16fb8d75-f23a-4d29-bd30-c65acc1704cf
[I 2025-03-30 03:20:16,774] Trial 0 finished with value: 0.760629081700653 and parameters: {'classifier': 'CatBoostClassifier', 'n_estimators': 66, 'depth': 13, 'learning_rate': 0.15070494931494266}. Best is trial 0 with value: 0.760629081700653.
[I 2025-03-30 03:20:16,996] Trial 1 finished with value: 0.7557110489137677 and parameters: {'classifier': 'LGBMClassifier', 'n_estimators': 125, 'max_depth': 8, 'learning_rate': 0.07821509944724654}. Best is trial 0 with value: 0.760629081700653.

[LightGBM] [Info] Number of positive: 171, number of negative: 320
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000367 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 583
[LightGBM] [Info] Number of data points in the train set: 491, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.348269 -> initscore=-0.626657
[LightGBM] [Info] Start training from score -0.626657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 170, number of negative: 321
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000078 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 582
[LightGBM] [Info] Number of data points in the train set: 491, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.346232 -> initscore=-0.635643
[LightGBM] [Info] Start training from score -0.635643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 170, number of negative: 321
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000054 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 581

[I 2025-03-30 03:20:17,035] Trial 2 finished with value: 0.7214714114354258 and parameters: {'classifier': 'DecisionTreeClassifier', 'max_depth': 6, 'min_samples_split': 12}. Best is trial 0 with value: 0.760629081700653.
[I 2025-03-30 03:20:18,540] Trial 3 finished with value: 0.7328535252565641 and parameters: {'classifier': 'XGBClassifier', 'n_estimators': 67, 'max_depth': 41, 'learning_rate': 0.25090403558981356}. Best is trial 0 with value: 0.760629081700653.
[I 2025-03-30 03:20:18,577] Trial 4 finished with value: 0.7491803278688525 and parameters: {'classifier': 'KNeighborsClassifier', 'n_neighbors': 46, 'weights': 'distance'}. Best is trial 0 with value: 0.760629081700653.

In [43]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'CatBoostClassifier', 'n_estimators': 66, 'depth': 13, 'learning_rate': 0.15070494931494266}
Best trial accuracy: 0.760629081700653

In [44]:
study.trials_dataframe()

   number     value  ... params_weights     state
0       0  0.760629  ...            NaN  COMPLETE
1       1  0.755711  ...            NaN  COMPLETE
2       2  0.721471  ...            NaN  COMPLETE
3       3  0.732854  ...            NaN  COMPLETE
4       4  0.749180  ...       distance  COMPLETE

[5 rows x 14 columns]

In [45]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
CatBoostClassifier        1
LGBMClassifier            1
DecisionTreeClassifier    1
XGBClassifier             1
KNeighborsClassifier      1
Name: count, dtype: int64

In [46]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
CatBoostClassifier        0.760629
DecisionTreeClassifier    0.721471
KNeighborsClassifier      0.749180
LGBMClassifier            0.755711
XGBClassifier             0.732854
Name: value, dtype: float64